### ISSUE TITLE
Project rename request

### ISSUE THREAD

**Issue by ZeroAbility** [FrazzIe/mumble-fivem-voip#38]
Greetings,

As a member of The Mumble team I am kindly requesting a rename of your project from "mumble-voip" to something more consistent with your project. We feel that since our group page has held this name for some time, your project name may lead to confusion in the developer and user community when trying to find both of our projects in GitHub. I would encourage you to search the new name you pick for your project in GitHub to make sure it is unique. I apologize if this causes any inconvenience to your developers and users.

Thank you,

**Comment by FrazzIe** [comment]
done

**Comment by nsinisterra** [comment]
It breaks GCPhone integration, a PR will be needed :/
